from enum import Enum


class DatasetColumns(str, Enum):
    """Columns in the training/synthetic/redesign/test metadata CSVs"""

    pdb_name = "pdb_name"
    processed_path = "processed_path"  # pkl file
    oligomeric_count = "oligomeric_count"
    oligomeric_detail = "oligomeric_detail"
    resolution = "resolution"
    structure_method = "structure_method"
    quaternary_category = "quaternary_category"
    num_chains = "num_chains"
    seq_len = "seq_len"
    modeled_seq_len = "modeled_seq_len"
    coil_percent = "coil_percent"
    helix_percent = "helix_percent"
    strand_percent = "strand_percent"
    radius_gyration = "radius_gyration"

    # cluster metadata (added by loading clusters csv)
    cluster = "cluster"

    # redesign columns
    example = "example"
    best_seq = "best_seq"  # best 1 redesign per structure
    best_rmsd = "best_rmsd"

    # added during load
    index = "index"


class DatasetProteinColumns(str, Enum):
    """
    Information about the protein, pickled in `processed_path`

    This code is not provided by MultiFlow, just the generated artifacts.

    Most fields and values seem straightforward from parsing the PDB file, but there are some oddities / potential bugs.

    For example, looking at `10mh`:
    1. 2 DNA molecules are included as chains and the protein is classified as a trimer.
    This is debatable, but reasonable, since the protein is binding something, and shouldn't be treated as a homomer.
    2. The chain IDs in the `pkl` are 26 (protein), 27 (DNA), 28 (DNA).
    There are some heteroatoms but unclear where these numbers come from. Probably not important that they are so high?

    """

    aatype = "aatype"  # AA sequence (N, )
    atom_positions = "atom_positions"  # all atom, (N, 37, 3)
    atom_mask = "atom_mask"  # all atom (N, 37)
    bb_mask = "bb_mask"  # alpha carbon  (N, )
    bb_positions = "bb_positions"  # alpha carbon (N, 3)
    residue_index = "residue_index"  # residue index (N, )
    chain_index = "chain_index"  # chain index (N, )
    b_factors = "b_factors"  # b factors (N, 37)
    modeled_idx = "modeled_idx"  # index of modeled residues (dropped in processing) i.e. in mask (N, )


class DatasetTransformColumns(str, Enum):
    """
    Columns generated by OpenFold data transform
    """

    # atom37_to_frames()
    rigidgroups_gt_frames = "rigidgroups_gt_frames"
    rigidgroups_gt_exists = "rigidgroups_gt_exists"
    rigidgroups_group_exists = "rigidgroups_group_exists"
    rigidgroups_group_is_ambiguous = "rigidgroups_group_is_ambiguous"
    rigidgroups_alt_gt_frames = "rigidgroups_alt_gt_frames"
    # atom37_to_torsion_angles()
    torsion_angles_sin_cos = "torsion_angles_sin_cos"
